### ISSUE TITLE
see in my https://github.com/GustiMuhammadAdzaky/CODEIGNITER4-CRUD

### ISSUE THREAD

**Issue by creatorclass** [creatorclass/disarpuskkr#2]
see in my https://github.com/GustiMuhammadAdzaky/CODEIGNITER4-CRUD

_Originally posted by @GustiMuhammadAdzaky in https://github.com/creatorclass/disarpuskkr/issues/1#issuecomment-1156761579_

**Comment by GustiMuhammadAdzaky** [comment]
try
